name: Print GitHub Event

on:
  push:
    tags:
      - '**'

jobs:
  print_event:
    runs-on: ubuntu-latest

    steps:
    - name: Print GitHub Event
      run: echo '${{ toJson(github.event) }}'

    - name: Fetch Tag Details
      run: |
        API_URL="https://api.github.com/repos/${{ github.event.repository.full_name }}/git/tags/${{ github.event.after }}"
        TAG_DETAILS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "$API_URL")
        echo "$TAG_DETAILS"